### ISSUE TITLE
FR:  Cura 3.5.1 AppImage

### ISSUE THREAD

**Issue by talldonkey** [TheAssassin/cura-type2-appimages#1]
Hi - Wondering if you would be kind enough to run your Type2 AppImage script in your pre-setup environment for the latest Cura 3.5.1 release, and publish to releases?  I'm looking to get Cura 3.5.1 working on crostini on a pixelbook.  It seems like that Type2 Appimages can be extracted and ran on pixelbook, but Type1 does not extract.

If you're curious, this is the full context -  https://www.reddit.com/r/Crostini/comments/9p8vzy/cura_351_on_pixelbook_xpost_from_chromeos/

**Comment by TheAssassin** [comment]
Sure thing. Didn't notice there was a new release. Build is in progress.

**Comment by talldonkey** [comment]
Thank you!  Successfully extracted the AppImage and ran it on pixelbook via Crostini.

**Comment by TheAssassin** [comment]
Feel free to open new issues for new releases if I don't build an AppImage in the meantime.

Oh, and please show your support for upstream type 2 AppImages in the upstream issues. Making Cura release type 2 AppImages would be the best solution.
