### ISSUE TITLE
FR:  Cura 3.6 Beta Type 2 AppImage

### ISSUE THREAD

**Issue by talldonkey** [TheAssassin/cura-type2-appimages#2]
Cura 3.6 Beta has been released.  Possible for a Type2 Appimage?

Usually I wouldn't bother with the beta releases, but 3.6 has a pretty shiny new feature - Gyroid infill!

**Comment by TheAssassin** [comment]
There's no GitHub release yet, so it'd require building it manually. But the feature sounds ~~useful~~ really awesome. I'll think about it.

**Comment by TheAssassin** [comment]
Added beta AppImage support to my script. Build in progress: https://travis-ci.org/TheAssassin/cura-type2-appimages/builds/449640582.

**Comment by TheAssassin** [comment]
New release has been uploaded. I'd like them to be prereleases by default, though. Fixed that manually. WIP in https://github.com/probonopd/uploadtool/issues/41.

**Comment by talldonkey** [comment]
Thank you!!
